name: Resume builder

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:


jobs:
  build-resumes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: latex
        root_file: "*.tex"

    - name: List files in latex directory
      run: ls latex

    - name: Rename PDF files
      run: |
        for file in latex/*.pdf; do
          mv "$file" "latex/aadi_manchekar_$(basename "$file")"
        done

    - name: List files in latex directory
      run: ls latex

    - name: Create Resumes subfolder and move PDFs
      run: |
        mkdir -p Resumes
        mv latex/*.pdf Resumes/

    - name: List files in Resumes directory
      run: ls Resumes

    - name: Delete tag
      run: gh release delete Aadi-Manchekar --cleanup-tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: Resumes
        workdir: Resumes
        tag: Aadi-Manchekar
